apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: cont1
          image: docker.io/ankit8840/php-mongodb-crud
          ports:
            - containerPort: 80
              hostPort: 80

